---
- hosts: ubuntu
  vars:
    username: "username"
    password: "password"

  tasks:
    - name: Install passlib package
      pip: name=passlib

    - name: Encrypt the password using passlib
      shell: python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt('{{ password }}')"
      register: Encrypted_password  

    - name: Trigger the username and password action on remote hosts
      shell: ansible-playbook /etc/ansible/password_reset.yml -e username="{{ username }}" -e  password='"{{ item }}"'
      with_items: "{{ Encrypted_password.stdout }}"

