---
- hosts: target
  vars:
    username: "username"
    password: "password"

  tasks:
    - name : Change User password
      user : name={{ username }} update_password=always password={{ password }}
